ALTER TABLE entries ADD COLUMN parent_view_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_edit_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_delete_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_comments_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_add_comment_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_reactions_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_negative_reactions_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_reaction_totals_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_negative_reaction_totals_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_reaction_ratios_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_view_negative_reaction_ratios_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_add_reaction_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN parent_add_negative_reaction_principal varchar(70) NOT NULL DEFAULT 'unset';
ALTER TABLE entries ADD COLUMN child_operations text NOT NULL DEFAULT '{}';
UPDATE entries SET add_comment_principal = 'signed' WHERE add_comment_principal = 'public';
UPDATE entries SET add_reaction_principal = 'signed' WHERE add_reaction_principal = 'public';
UPDATE entries SET add_negative_reaction_principal = 'signed' WHERE add_negative_reaction_principal = 'public';
ALTER TABLE entries ALTER COLUMN add_comment_principal SET DEFAULT 'signed';
ALTER TABLE entries ALTER COLUMN add_reaction_principal SET DEFAULT 'signed';
ALTER TABLE entries ALTER COLUMN add_negative_reaction_principal SET DEFAULT 'signed';
