ALTER TABLE entries RENAME id TO entry_id;
ALTER TABLE entries ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE entries DROP CONSTRAINT entries_pkey;
ALTER TABLE entries ADD PRIMARY KEY(id);
ALTER TABLE entries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE entries ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;
