package org.moera.node.event.model;

public enum EventType {

    SUBSCRIBED,
    PROFILE_UPDATED,
    NODE_SETTINGS_CHANGED,
    CLIENT_SETTINGS_CHANGED,
    POSTING_ADDED,
    POSTING_UPDATED,
    POSTING_DELETED,
    POSTING_RESTORED,
    REGISTERED_NAME_CHANGED,
    REGISTERED_NAME_OPERATION_STATUS,
    REMOTE_POSTING_VERIFIED,
    REMOTE_POSTING_VERIFICATION_FAILED

}
