package org.moera.node.event.model;

public enum EventType {

    SUBSCRIBED,
    PROFILE_UPDATED,
    NODE_SETTINGS_CHANGED,
    CLIENT_SETTINGS_CHANGED,
    POSTING_ADDED,
    POSTING_UPDATED,
    POSTING_DELETED,
    POSTING_RESTORED,
    NODE_NAME_CHANGED,
    REGISTERED_NAME_OPERATION_STATUS,
    REMOTE_POSTING_VERIFIED,
    REMOTE_POSTING_VERIFICATION_FAILED,
    POSTING_REACTIONS_CHANGED,
    REMOTE_REACTION_VERIFIED,
    REMOTE_REACTION_VERIFICATION_FAILED,
    DRAFT_POSTING_ADDED,
    DRAFT_POSTING_UPDATED,
    DRAFT_POSTING_DELETED,
    POSTING_DRAFT_REVISION_UPDATED,
    POSTING_DRAFT_REVISION_DELETED,
    STORY_ADDED,
    STORY_DELETED,
    STORY_UPDATED

}
